version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: mediassist-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: mediassist
      POSTGRES_PASSWORD: mediassist123
      POSTGRES_DB: mediassist_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mediassist-net

volumes:
  pgdata:

networks:
  mediassist-net:
    driver: bridge
